version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Survive_Hertz_Massager_Rage_Creative_Grievous_Mossy_Purify144!"
      ACCEPT_EULA: "Y"
      # volumes:
      #   - ./data:/var/opt/mssql/data
  backend:
    build: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      DB_PASSWORD: "Survive_Hertz_Massager_Rage_Creative_Grievous_Mossy_Purify144!"
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
